# typed: false
# frozen_string_literal: true

# This file was generated by an AI. Feel free to edit it so that it meets your needs.
class Dscleaner < Formula
  desc "Removes macOS junk (.DS_Store, ._* AppleDouble, ...) and keeps it off copies"
  homepage "https://github.com/t2o0n321/dscleaner"
  url "https://github.com/t2o0n321/dscleaner/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "53daf00bdea1d31628d6de4eb83b61f6fdb216b9b9696d2f25ad1e82c7e382e0"
  license "MIT"

  def install
    system "make", "-C", "core"
    bin.install "core/bin/dscleaner"
    # Short alias: `dc`.
    bin.install_symlink "dscleaner" => "dc"
  end

  test do
    # Create dummy macOS junk: a .DS_Store and an AppleDouble side-car.
    (testpath/".DS_Store").write ""
    (testpath/"._payload").write ""
    (testpath/"keep.txt").write "real"
    # Run the cleaner on the test path.
    system "#{bin}/dscleaner", testpath.to_s, "-n"
    # Junk is removed; real files are left alone.
    assert_not_predicate testpath/".DS_Store", :exist?
    assert_not_predicate testpath/"._payload", :exist?
    assert_predicate testpath/"keep.txt", :exist?
  end
end
