# typed: false
# frozen_string_literal: true

# This file was generated by an AI. Feel free to edit it so that it meets your needs.
class Dscleaner < Formula
  desc "A simple and efficient tool for removing .DS_Store files"
  homepage "https://github.com/t2o0n321/dscleaner"
  url "https://github.com/t2o0n321/dscleaner/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "53daf00bdea1d31628d6de4eb83b61f6fdb216b9b9696d2f25ad1e82c7e382e0"
  license "MIT"

  def install
    system "make"
    bin.install "bin/dscleaner"
  end

  test do
    # Create a dummy .DS_Store file
    (testpath/".DS_Store").write ""
    # Run the cleaner on the test path
    system "#{bin}/dscleaner", testpath.to_s, "-n"
    # Assert that the file was removed
    assert_not_predicate testpath/".DS_Store", :exist?
  end
end
